config {
    type: 'assertion',
    name: 'abcde'
}

select 
    date, 
    client_id,
    project_id,
    source,
    medium,
    campaign_name,
    count(*) as cnt
from 
    ${ref('l2_campaigns_monkeymum_com')}
group by 
    all 
having cnt > 1
union all
select 
    date, 
    client_id,
    project_id,
    source,
    medium,
    campaign_name,
    count(*) as cnt
from 
    ${ref('l2_ga4_ecomm_monkeymum_com')}
group by 
    all 
having cnt > 1